### ISSUE TITLE
Fix navigation in documentation breadcrumbs

### ISSUE THREAD

**Issue by mppfiles** [javalite/javalite-site#18]
Second-level links in breadcrumbs must point to the documentation root of each javalite component, instead of the component start page. This speeds up navigation between pages a lot.
Example: in [app_context page](http://javalite.io/app_context) the breadcrumb could point to `/documentation#activeweb` instead of `/activeweb`.

What do you think? If you agree, I can send a PR editing all .properties files.

**Comment by ipolevoy** [comment]
@mppfiles that would be fantastic, go ahead

**Comment by ipolevoy** [comment]
@mppfiles great work! I think that the ActiveWeb pages are way too long and need to be broken into smaller pages, what do  you think?

**Comment by mppfiles** [comment]
I feel comfortable with the page length right now, maybe we can improve some of them. There are other frameworks with a [one-page documentation](http://sparkjava.com/documentation) indeed :wink:

**Comment by ipolevoy** [comment]
true, but in some  cases I saw the collapsible menu run outside screen boundary
