### ISSUE TITLE
Document some examples of Base/DB classes

### ISSUE THREAD

**Issue by mppfiles** [javalite/javalite-site#29]
ActiveJDBC can be used without the ORM part, just as a simple JDBC wrapper, using Base and DB classes, and works really great.
It would be nice to document the underlying methods with some examples, like `findAll()`, `exec()`, `firstCell()`, etc.

**Comment by ipolevoy** [comment]
@mppfiles agree, will document this.

**Comment by ipolevoy** [comment]
@mppfiles here it is: http://localhost:8080/basic_database_operations, let me know what you  think

**Comment by mppfiles** [comment]
Great work, thanks! Just found a few typos, will make a new PR :+1:
