### ISSUE TITLE
Add ${context_path} documentation in views

### ISSUE THREAD

**Issue by mppfiles** [javalite/javalite-site#8]
It would be nice to mention the useful `${context_path}` parameter in the [context-parameters](http://javalite.io/context-parameters) page. Is there any other parameter worth mentioning?

**Comment by ipolevoy** [comment]
good point, let me look through code if I'm missing anything else.

**Comment by ipolevoy** [comment]
docs added,  please take a look and feel free to close this.

**Comment by mppfiles** [comment]
looks great! thanks!

**Comment by ipolevoy** [comment]
:+1:
